# Form implementation generated from reading ui file 'historyWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_History(object):
    def setupUi(self, History):
        History.setObjectName("History")
        History.resize(800, 760)
        History.setMinimumSize(QtCore.QSize(800, 760))
        History.setMaximumSize(QtCore.QSize(800, 760))
        self.label = QtWidgets.QLabel(parent=History)
        self.label.setGeometry(QtCore.QRect(70, 40, 241, 81))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.taskHistoryTextBrowser = QtWidgets.QTextBrowser(parent=History)
        self.taskHistoryTextBrowser.setGeometry(QtCore.QRect(50, 120, 571, 371))
        self.taskHistoryTextBrowser.setObjectName("taskHistoryTextBrowser")
        self.completedTaskCountLabel = QtWidgets.QLabel(parent=History)
        self.completedTaskCountLabel.setGeometry(QtCore.QRect(340, 60, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.completedTaskCountLabel.setFont(font)
        self.completedTaskCountLabel.setObjectName("completedTaskCountLabel")
        self.clearHistoryButton = QtWidgets.QPushButton(parent=History)
        self.clearHistoryButton.setGeometry(QtCore.QRect(50, 600, 113, 32))
        self.clearHistoryButton.setObjectName("clearHistoryButton")
        self.backButton = QtWidgets.QPushButton(parent=History)
        self.backButton.setGeometry(QtCore.QRect(540, 600, 113, 32))
        self.backButton.setObjectName("backButton")

        self.retranslateUi(History)
        QtCore.QMetaObject.connectSlotsByName(History)

    def retranslateUi(self, History):
        _translate = QtCore.QCoreApplication.translate
        History.setWindowTitle(_translate("History", "History"))
        self.label.setText(_translate("History", "Completed Tasks:"))
        self.completedTaskCountLabel.setText(_translate("History", "0"))
        self.clearHistoryButton.setText(_translate("History", "Clear"))
        self.backButton.setText(_translate("History", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    History = QtWidgets.QWidget()
    ui = Ui_History()
    ui.setupUi(History)
    History.show()
    sys.exit(app.exec())
